# Generated by Django 2.2.1 on 2019-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('form', models.CharField(max_length=120)),
                ('authorPhoto', models.CharField(max_length=120)),
                ('book', models.CharField(max_length=120)),
                ('uploader', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('role', models.CharField(default='ROLE_USER', max_length=120)),
            ],
        ),
    ]
